name: chat_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  json_theme: ^6.4.0
  http_interceptor: ^1.0.2
  http: ^0.13.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/themes/
    - assets/lottie/
    - assets/images/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: MontserratItalic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf

    - family: MontserratBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
